### ISSUE TITLE
Minuit.mncontour fails with ValueError depending on parameter order

### ISSUE THREAD

**Issue by adonath** [scikit-hep/iminuit#669] opened 2021-07-07 08:26 UTC
In the process of adding [support for iminuit v2.0 for Gammapy](https://github.com/gammapy/gammapy/pull/3409) I came across the following bug:

```python3
import numpy as np
from iminuit import Minuit
from iminuit.cost import LeastSquares

def line(x, a, b, c):
    return a + x * b + c * x ** 2

np.random.seed(1)
data_x = np.linspace(0, 1, 10)
data_yerr = 0.1
data_y = line(data_x, 1, 2, 3) + data_yerr * np.random.randn(len(data_x))

least_squares = LeastSquares(data_x, data_y, data_yerr, line)

m = Minuit(least_squares, a=0, b=0, c=0)

m.migrad()
m.hesse()

m.mncontour(x="b", y="c") # works
m.mncontour(x="c", y="b") # fails
```
Fails with:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-d39f11243df4> in <module>
     19 
     20 m.mncontour(x="a", y="b")
---> 21 m.mncontour(x="c", y="b")

~/opt/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/iminuit/minuit.py in mncontour(self, x, y, cl, size)
   1395         vary = self._free_parameters()
   1396         if x not in vary or y not in vary:
-> 1397             raise ValueError("mncontour cannot be run on fixed parameters.")
   1398 
   1399         with TemporaryErrordef(self._fcn, factor):

ValueError: mncontour cannot be run on fixed parameters.
```
But all parameters are free to vary.

From a quick look [here](https://github.com/scikit-hep/iminuit/blob/develop/src/iminuit/minuit.py#L1785) it seems `._free_parameters()` returns a generator, which might be empty after the first iteration checking for `x`, depending on the position of `x` in the list. So the second check for `y` must fail...

**Comment by HDembinski** [comment] 2021-07-22 10:08
Wow, thanks for reporting this and investigating the cause, will be fixed immediately.

**Closed** 2021-07-22 12:50 UTC
