### ISSUE TITLE
Provided gradient not being used?

### ISSUE THREAD

**Issue by DavidMStraub** [scikit-hep/iminuit#644] opened 2021-04-27 11:34 UTC
Hi iminuit team!

I am using iminuit v2.4.0 with Python 3.8.5 to minimize a function where I also know the gradient (it's automatically differentiated using `jax`). Schematically, my code looks like this:

```python
from jax import grad
from iminuit import Minuit

def negative_log_prob(x):
    # ...
    return chi2 / 2

negative_dlog_prob = grad(negative_log_prob)

x0 = ...
limits = ...

m = Minuit(negative_log_prob, x0, grad=negative_dlog_prob)
m.limits = limits
m.errordef = Minuit.LIKELIHOOD
m.strategy = 0
m.migrad(ncall=10)
```

My likelihood is quite slow to evaluate (~1 second) and I have 25 parameters. When I run migrad, it takes very long and in the log output I can see things like 

```
D MnSeedGenerator 25 free parameters, FCN pointer 0x7ffcaeef0160
D InitialGradientCalculator Calculating initial gradient at point 
[...]
D InitialGradientCalculator Computed initial gradient for parameter [...]
D InitialGradientCalculator Computed initial gradient for parameter [...]
[...]
D InitialGradientCalculator Computed initial gradient for parameter [...]
D Numerical2PGradientCalculator Assumed precision eps 8.88178e-16 eps2 5.96046e-08
D Numerical2PGradientCalculator Calculating gradient around value 0.376557 at point 
[...]
D Numerical2PGradientCalculator  parameter cycle              x           step             f1             f2            grd             g2
D Numerical2PGradientCalculator [...]
```

So it looks like it *does* compute the gradient numerically itself rather than using the provided gradient, which takes very long due to the large number of parameters.

Is there something obvious that I could be doing wrong?

Thanks!

**Comment by HDembinski** [comment] 2021-04-30 15:42
There was a change in the Minuit2 C++ code recently to compute the initial gradient still numerically. The reasoning was that the InitialGradientCalculator also computes an estimate for the step size. Lorenzo Moneta from the ROOT team argued that this makes the fit more stable. So what you see is not a bug. You should see that Migrad uses the analytical gradient after the the initial numerical computation.

**Comment by HDembinski** [comment] 2021-04-30 15:46
@lmoneta FYI

**Comment by HDembinski** [comment] 2021-04-30 15:47
@DavidMStraub Thank you for a very clear issue write-up, btw!

**Comment by HDembinski** [comment] 2021-07-04 13:51
I am closing this, as this issue would have to be addressed in ROOT.

**Closed by HDembinski** 2021-07-04 13:51 UTC

**Comment by DavidMStraub** [comment] 2021-07-04 15:47
@HDembinski sorry for not reaction to this and thanks for your explanation! I con confirm that it *did* work after I was patient enough to wait for the initial step to complete.
