### ISSUE TITLE
iminuit v2 seems to get more stuck

### ISSUE THREAD

**Issue by mayou36** [scikit-hep/iminuit#613] opened 2021-02-22 19:49 UTC
We're extensively trying out the new iminuit v2 version and figured that overall, it seems sometimes to "terminate" to quickly, or to get stuck somehow. Even for actually quite simple fits, and it is not clear to us, why it happens.

These all used to work quite stable in v1. Since it's likelihood fitting, it's not trivial to extract a good example into a few lines, but I'll try to provide something and update the thread.

For now, I have the stacktrace that often looks similar (this VariableMetricBuilder that repeats itself a lot), in this case fitting a DoubleCB to data (100k), so a rather simple fit actually.

Maybe you do already have an idea when looking at things or have experienced something different? Could that be because of new heuristics?

In any case, many thanks for your advice!

This is an example output:
```
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 5.90577e+09 Requested 0.001
W MnPosDef non-positive diagonal element in covariance matrix[ 1 ] = -10827.5
W MnPosDef non-positive diagonal element in covariance matrix[ 2 ] = -18139.8
W MnPosDef non-positive diagonal element in covariance matrix[ 3 ] = -10900
W MnPosDef non-positive diagonal element in covariance matrix[ 4 ] = -447.659
W MnPosDef Added to diagonal of Error matrix a value 18140.3
W MnPosDef Matrix forced pos-def by adding to diagonal 108.29
W DavidonErrorUpdator delgam < 0 : first derivatives increasing along search line
W BasicMinimumError::Hessian Inversion fails; return diagonal matrix
W VariableMetricBuilder Matrix not pos.def, gdel = 1.08045e+09 > 0
W MnPosDef non-positive diagonal element in covariance matrix[ 2 ] = -0.0146245
W MnPosDef Added to diagonal of Error matrix a value 0.514625
W VariableMetricBuilder gdel = -1.10241e+12
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 3.13298e+14 Requested 0.001
W VariableMetricBuilder FunctionMinimum is invalid after second try
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 5.51203e+11 Requested 0.001
W VariableMetricBuilder No convergence; Edm 5.51203e+11 is above tolerance 0.01
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 5.51203e+11 Requested 0.001
W VariableMetricBuilder No convergence; Edm 5.51203e+11 is above tolerance 0.01
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 5.51203e+11 Requested 0.001
W VariableMetricBuilder No convergence; Edm 5.51203e+11 is above tolerance 0.01
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 5.51203e+11 Requested 0.001
W VariableMetricBuilder No convergence; Edm 5.51203e+11 is above tolerance 0.01
```

**Comment by HDembinski** [comment] 2021-03-09 11:45
Not sure what to say, the EDM value looks problematic, probably a numerical issue in the cost function? If your cost function has numerical issues, then things will stop working as we keep to improve implementation details in Minuit, while other pathological cases will start working (but you don't notice those cases).

**Comment by HDembinski** [comment] 2021-03-10 13:01
I am tentatively closing this, but please reopen if you found more concrete evidence that there is a performance regression. 

In this particular case it looks like you have some parameter which are highly correlated.

**Comment by mayou36** [comment] 2021-03-14 14:18
Whenever you have time to have a look (no hurry), I've got an example of where it got stuck, not as a standalone but I've extracted information.


It's a simple fit of a Gaussian + Exponential to around 20k toy data. Nothing difficult at all actually. Internal gradient, strategy 0, tol is 0.1. Run migrad until it stopped (output below). I don't understand how it can possibly get stuck here.

I've made profile plots where it got stuck. The initial values are

<table>\n    <tr>\n        <td></td>\n        <th title="Variable name"> Name </th>\n        <th title="Value of parameter"> Value </th>\n        <th title="Hesse error"> Hesse Error </th>\n        <th title="Minos lower error"> Minos Error- </th>\n        <th title="Minos upper error"> Minos Error+ </th>\n        <th title="Lower limit of the parameter"> Limit- </th>\n        <th title="Upper limit of the parameter"> Limit+ </th>\n        <th title="Is the parameter fixed in the fit"> Fixed </th>\n    </tr>\n    <tr>\n        <th> 0 </th>\n        <td> mu </td>\n        <td> 2.50 </td>\n        <td> 0.03 </td>\n        <td>  </td>\n        <td>  </td>\n        <td> -5 </td>\n        <td> 9 </td>\n        <td>  </td>\n    </tr>\n    <tr>\n        <th> 1 </th>\n        <td> sigma </td>\n        <td> 0.60 </td>\n        <td> 0.03 </td>\n        <td>  </td>\n        <td>  </td>\n        <td> 0.01 </td>\n        <td> 10 </td>\n        <td>  </td>\n    </tr>\n    <tr>\n        <th> 2 </th>\n        <td> lambda </td>\n        <td> -0.015 </td>\n        <td> 0.001 </td>\n        <td>  </td>\n        <td>  </td>\n        <td> -0.5 </td>\n        <td> -0.0003 </td>\n        <td>  </td>\n    </tr>\n</table>

The covariance:
<table>\n    <tr>\n        <td></td>\n        <th> mu </th>\n        <th> sigma </th>\n        <th> lambda </th>\n    </tr>\n    <tr>\n        <th> mu </th>\n        <td> 18.3 </td>\n        <td style="background-color:rgb(250,250,250);color:black"> 0.00134 <strong>(0.000)</strong> </td>\n        <td style="background-color:rgb(250,250,250);color:black"> -0.000142 </td>\n    </tr>\n    <tr>\n        <th> sigma </th>\n        <td style="background-color:rgb(250,250,250);color:black"> 0.00134 <strong>(0.000)</strong> </td>\n        <td> 8.59 </td>\n        <td style="background-color:rgb(250,250,250);color:black"> 0.00011 </td>\n    </tr>\n    <tr>\n        <th> lambda </th>\n        <td style="background-color:rgb(250,250,250);color:black"> -0.000142 </td>\n        <td style="background-color:rgb(250,250,250);color:black"> 0.00011 </td>\n        <td> 0.03 </td>\n    </tr>\n</table>

![image](https://user-images.githubusercontent.com/17454848/111071312-dc120100-84d5-11eb-8d41-a1b1e16cbb70.png)

![image](https://user-images.githubusercontent.com/17454848/111071317-e3390f00-84d5-11eb-9a73-5f5b0eb29623.png)

![image](https://user-images.githubusercontent.com/17454848/111071322-e92ef000-84d5-11eb-899a-20f4d5a171ff.png)

This is a zoomed in version on the lambda parameter to check for numerical issues, but it seems all fine.

![image](https://user-images.githubusercontent.com/17454848/111071516-d0730a00-84d6-11eb-94e1-25b571be4fd0.png)


The output is:

<details>
<summary>Details</summary>




```W VariableMetricBuilder Matrix not pos.def, gdel = 8775.68 > 0
W MnPosDef non-positive diagonal element in covariance matrix[ 0 ] = -2.81463e-05
W MnPosDef non-positive diagonal element in covariance matrix[ 1 ] = -5.44292e-05
W MnPosDef Added to diagonal of Error matrix a value 0.500055
W VariableMetricBuilder gdel = -9.386e+07
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 7924.45 Requested 0.0001
W MnPosDef Matrix forced pos-def by adding to diagonal 0.362895
W DavidonErrorUpdator delgam < 0 : first derivatives increasing along search line
W VariableMetricBuilder Matrix not pos.def, gdel = 3533.6 > 0
W MnPosDef non-positive diagonal element in covariance matrix[ 0 ] = -4.2103e-05
W MnPosDef non-positive diagonal element in covariance matrix[ 1 ] = -5.01915e-05
W MnPosDef Added to diagonal of Error matrix a value 0.500051
W VariableMetricBuilder gdel = -9.41755e+07
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 9.50042e+06 Requested 0.0001
W VariableMetricBuilder FunctionMinimum is invalid after second try
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 4.70858e+07 Requested 0.0001
W VariableMetricBuilder No convergence; Edm 4.70858e+07 is above tolerance 0.001
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 4.70858e+07 Requested 0.0001
W VariableMetricBuilder No convergence; Edm 4.70858e+07 is above tolerance 0.001
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 4.70858e+07 Requested 0.0001
W VariableMetricBuilder No convergence; Edm 4.70858e+07 is above tolerance 0.001
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 4.70858e+07 Requested 0.0001
W VariableMetricBuilder No convergence; Edm 4.70858e+07 is above tolerance 0.001
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 4.70858e+07 Requested 0.0001
W VariableMetricBuilder No convergence; Edm 4.70858e+07 is above tolerance 0.001
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 4.70858e+07 Requested 0.0001
W VariableMetricBuilder No convergence; Edm 4.70858e+07 is above tolerance 0.001
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 4.70858e+07 Requested 0.0001
W VariableMetricBuilder No convergence; Edm 4.70858e+07 is above tolerance 0.001
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 4.70858e+07 Requested 0.0001
W VariableMetricBuilder No convergence; Edm 4.70858e+07 is above tolerance 0.001
W VariableMetricBuilder No improvement in line search
W VariableMetricBuilder Iterations finish without convergence; Edm 4.70858e+07 Requested 0.0001
W VariableMetricBuilder No convergence; Edm 4.70858e+07 is above tolerance 0.001
```

</details>

**Comment by HDembinski** [comment] 2021-07-04 17:21
This looks like a problem in your model.

You can see in the Minuit warnings that at some point during the minimization the diagonal elements of the covariance matrix become negative. That should never happen. Usually, this is a problem with the numerical accuracy of the model. Does you model compute in float32 or float64 precision? If it is float32, you need to set the precision parameter of Minuit accordingly.

Apart from that, the model has kinks. The profiles along all parameters show plateaus. Migrad expects your function to be twice differentiable everywhere within the parameter bounds.

**Closed by HDembinski** 2021-07-04 17:21 UTC

**Comment by mayou36** [comment] 2021-07-05 08:03
I agree, that hints to some numerical issues.

> If your cost function has numerical issues, then things will stop working as we keep improving implementation details in Minuit, while other pathological cases will start working (but you don't notice those cases).

I see, that is actually good news.

> Apart from that, the model has kinks. The profiles along all parameters show plateaus, that is bad. Migrad expects your function to be twice differentiable everywhere within the parameter bounds.

It is, but it's not visible here, I noticed that as well that it has problems otherwise.

Thanks for this, I am still a bit puzzled to why the model does no behave nicely, but I'll check it (yes, it's float64).
