### ISSUE TITLE
Latest bugfix release contains breaking changes

### ISSUE THREAD

**Issue by mayou36** [scikit-hep/iminuit#337] opened 2019-05-17 10:41 UTC
It seems like 1.3.5 contains breaking changes, which are also not documented in the release notes

m.values does not return a dict anymore but a tuple (so e.g. the example in the README is wrong now). This breaks existing code relying on the fact that it is a mapping and not a tuple.

I would suggest to remove this release and make a minor (1.4.0) release? Or restore the mapping behavior (which seems more convenient to me).

**Comment by HDembinski** [comment] 2019-05-17 10:48
I cannot reproduce this. `m.values` does not return a dict, that's true, but this change was already made a few versions prior. The object that `m.values` returns acts like a dict, however, you should be able to use it like at dict. In addition you can use it like a tuple. By that I mean you can pass either a string of the parameter name or the parameter index.

**Comment by HDembinski** [comment] 2019-05-17 10:51
Could you send me a minimal code snipped which demonstrates the wrong behavior?

**Comment by cdeil** [comment] 2019-05-17 10:53
Something changed. When I update `iminuit` from 1.3.3 to 1.3.5, then I get these fails in Gammapy:
https://gist.github.com/cdeil/877aa2895cc26f04dce4c1c6cc40d67f

**Comment by HDembinski** [comment] 2019-05-17 10:57
So the return value of the minos call changed. That was not intended. I will investigate and fix this get the previous behavior. Thank you for the quick feedback and sorry for the inconvenience. If you update that fast, I could do a release candidate next for you to check.

**Comment by mayou36** [comment] 2019-05-17 10:57
Yes, sorry, it's not in `m.values`, but in the minimization result. Here a snippet:
```python
result = m.migrad(lambda x: x**2)
param_result = result[1]
value = param_result[0]["value"]  # this used to work
```

**Comment by HDembinski** [comment] 2019-05-17 10:58
Thank you for the minimal example, I should be able to fix this quickly.

**Comment by mayou36** [comment] 2019-05-17 10:59
Perfect, thanks a lot!

**Comment by cdeil** [comment] 2019-05-17 11:03
In Gammapy, it's failing because `minuit.get_param_states()[0]["has_limits"]` no longer works:
https://gist.github.com/cdeil/e4b9a40ea840149ce5be7325358bcd34

@HDembinski - Should I send a PR adding a travis-ci build with Gammapy now?
We don't use much from the `iminuit` API, and really a separate repo on integration testing might be better (like e.g. what Numba does: https://github.com/numba/numba-integration-testing), but probably just adding a simple build to the exiting CI is an improvement for now?

**Comment by HDembinski** [comment] 2019-05-17 11:50
@cdeil Yes, please, that would be very much appreciated. We can set it up so that the integration tests only run on the master branch, which is not updated frequently, but all releases are always based on the master. Adding a separate repo sounds nice, but seems overkill.

**Comment by HDembinski** [comment] 2019-05-18 18:52
Fixed in develop

**Closed by HDembinski** 2019-05-18 18:52 UTC
Labels: bug

**Comment by cdeil** [comment] 2019-05-19 08:55
@HDembinski - Thanks!

Gammapy CI is currently broken because of this. If you can put out 1.3.6 soon (say next week) that would be great. Otherwise I'd change the Gammapy CI files to avoid 1.3.5 and pin to an older version.

**Comment by HDembinski** [comment] 2019-05-19 09:14
@cdeil We am hurrying to make a new release, you will get it early next week. Henry wants to get Azure support in as well, I am waiting for that to complete.

**Comment by HDembinski** [comment] 2019-05-19 09:15
You can help me by responding to https://github.com/gammapy/gammapy/issues/2144

**Comment by cdeil** [comment] 2019-05-19 09:23
@HDembinski - That's great, thank you!
