### ISSUE TITLE
Bug in main MIGRAD loop when call limit is exhausted

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/iminuit#637] opened 2021-04-06 10:23 UTC
Hii - I'm confused about the `maxfun` option. Consider this example. I would expect `r.nfev <= 300`  but what I get onn my machine is `r.nfev = 475`. 

```
def fun(x):
  return ((x-1.2)**4).sum()
r = iminuit.minimize(fun,x0 = 10*np.ones(10),options = dict(maxfun = 300))
print(r.x)
print(r.nfev)
```

Am I mis-interpreting the option?

**Comment by HDembinski** [comment] 2021-04-08 10:59
This is normal and also explained in the docs, although not for iminuit.minimize (that should be fixed), see https://iminuit.readthedocs.io/en/stable/reference.html#iminuit.Minuit.migrad

**Comment by HDembinski** [comment] 2021-04-08 11:03
MIGRAD stops only after a full iteration of the algorithm, which involves several function calls to compute the gradient numerically per iteration. Since your model has 10 parameters, there are 10 x 2 per iteration. Since you use the default strategy, MIGRAD also calls HESSE to compute the covariance matrix. The algorithm never stops while HESSE runs, which adds even more function calls to the budget. I suppose that is what happens here.

**Comment by HDembinski** [comment] 2021-04-08 11:21
While all this is true, on closer inspection, there also seems to be a bug in C++ MIGRAD that triggers extra iterations although the loop should terminate.

Code to reproduce:
```py
m = Minuit(lambda x: ((x - 1.2)**4).sum(), np.ones(10)*10)
m.print_level = 2
m.migrad(ncall=200)
```
Output:
```
I MnSeedGenerator Initial state: FCN =         59969.536 Edm =       39979.71978 NCalls =     41
I VariableMetricBuilder Start iterating until Edm is < 0.0002 with call limit = 200
I VariableMetricBuilder    0 - FCN =         59969.536 Edm =       39979.71978 NCalls =     41
I VariableMetricBuilder    1 - FCN =       112.3832533 Edm =       3.243367167 NCalls =     88
I VariableMetricBuilder    2 - FCN =      0.1387281577 Edm =   0.0003372366983 NCalls =    137
I VariableMetricBuilder    3 - FCN =   0.0001849058771 Edm =   3.896675319e-07 NCalls =    186
W MnHesse Maximum number of allowed function calls exhausted; will return diagonal matrix
I VariableMetricBuilder After Hessian
I VariableMetricBuilder    4 - FCN =   0.0001849058771 Edm =   3.896675319e-07 NCalls =    201
W VariableMetricBuilder Invalid Hessian - exit the minimization
I MnSeedGenerator Initial state: FCN =   0.0001849058771 Edm =   0.0001232705833 NCalls =     41
I VariableMetricBuilder Start iterating until Edm is < 0.0002 with call limit = 200
I VariableMetricBuilder    0 - FCN =   0.0001849058771 Edm =   0.0001232705833 NCalls =     41
I VariableMetricBuilder    1 - FCN =   3.465144998e-07 Edm =   1.003952412e-08 NCalls =     88
I VariableMetricBuilder After Hessian
I VariableMetricBuilder    2 - FCN =   3.465144998e-07 Edm =   2.309705122e-07 NCalls =    174
```
Although it says "exit the minimization" the iteration actually restarts. This must be a bug.

**Comment by HDembinski** [comment] 2021-04-08 11:22
- [ ] Add docstring about maxfun being possibly violated in iminuit.minimize
- [ ] Fix termination of main loop in C++ Migrad upstream in ROOT

**Comment by lukasheinrich** [comment] 2021-04-12 08:44
thanks @HDembinski - out of curiosity, how does the number 49 result from the 10-parameters?

**Comment by HDembinski** [comment] 2021-04-12 10:50
Magic

**Comment by lukasheinrich** [comment] 2021-04-12 11:05
meaning it varies per iteration of the MIGRAD alg? From `Since your model has 10 parameters, there are 49 calls per iteration.` it sounded like some kind of derivation was possible.. I wonder whether supporting the `maxiter` kw that `scipy` uses makes sense that limits the number of MIGRAD iterations that are allowed (however many function calls those then might be)

**Comment by HDembinski** [comment] 2021-04-12 13:01
We cannot support `maxiter`, because C++ Minuit does not allow you to stop on the number of iterations, it only supports stopping on the number of calls.

**Comment by HDembinski** [comment] 2021-04-12 13:12
I do agree that 49 calls per iteration is a lot and frankly more than I would expect. I expect 1 + 2 * 10 calls to compute the function value and the gradient. Maybe a couple more for a linesearch. The number of calls is not always the same, it depends on various things.

**Comment by HDembinski** [comment] 2021-04-12 17:53
It turns out that the gradient calculator in MINUIT uses 4 function calls per parameter and not only 2, which explains the order of magnitude, so under normal conditions you get 41 function calls. Since the artificial function here is not parabolic, the newton step does not work and MIGRAD has to spend some extra calls on a line search. This adds 8 more function calls.

**Comment by HDembinski** [comment] 2021-04-15 09:38
I found the problem, MnHesse does not report the call exhaustion via the function minimum. That's is why the flag "reached_call_limit" in FMin is false although it should be true. iminuit then repeats the minimization (the "iterate" feature). To fix this, the core issue needs to be fixed in C++ Minuit2. I am currently working on a series of patches toward that end.
https://github.com/root-project/root/pull/7882

**Comment by lukasheinrich** [comment] 2021-04-15 10:06
awesome! So if I understand correctly from your explanations

`MIGRAD stops only after a full iteration of the algorithm,` meaning you can't stop mid-way.. so the number of function calls might exceed by the number of calls needed to finish the iteration once the limit has been reached.

but also MIGRAD doesn't allow stopping after a fixed set of iterations (even though that seems to be the atomic unit of ), and each iteration might have a varying number of functoinn calls (dep. on how much line search is needed) so specifying `maxfun` is at most a rough guide (by trying to guess average #funcalls/iteration )

did I get that right?

**Closed** 2021-05-13 23:13 UTC
Labels: bug
