### ISSUE TITLE
Covariance matrix compatibility with uncertainties

### ISSUE THREAD

**Issue by APN-Pucky** [scikit-hep/iminuit#756] opened 2022-06-10 07:53 UTC
Following the Quick start <https://iminuit.readthedocs.io/en/stable/notebooks/basic_tutorial.html> I tried to use it with the uncertainties package <https://github.com/lebigot/uncertainties>. 
I encountered following error:
```py
>>> import uncertainties as unc
>>> unc.correlated_values(m.values, m.covariance)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-5b19c7ec7df3> in <module>
      1 import uncertainties as unc
----> 2 unc.correlated_values(m.values, m.covariance)

/opt/conda/lib/python3.6/site-packages/uncertainties/core.py in correlated_values(nom_values, covariance_mat, tags)
    184             # separates back the nominal values and the standard deviations:
    185             list(zip(nom_values, std_devs)),
--> 186             covariance_mat/norm_vector/norm_vector[:,numpy.newaxis],
    187             tags)
    188 

/opt/conda/lib/python3.6/site-packages/iminuit/util.py in __getitem__(self, key)
    225         var2pos = self._var2pos or {}
    226         if isinstance(key, tuple):  # tuple is special case for __getitem__
--> 227             key = tuple(var2pos.get(k, k) for k in key)
    228         elif isinstance(key, str):
    229             key = var2pos[key]

/opt/conda/lib/python3.6/site-packages/iminuit/util.py in <genexpr>(.0)
    225         var2pos = self._var2pos or {}
    226         if isinstance(key, tuple):  # tuple is special case for __getitem__
--> 227             key = tuple(var2pos.get(k, k) for k in key)
    228         elif isinstance(key, str):
    229             key = var2pos[key]

TypeError: unhashable type: 'slice'
```
I am not sure if this is intended behavior and if it requires a fix either on the iminuit or uncertainties side.
Nonetheless, the work around/solution I found for this is to avoid the custom `__getitem__` function in `Matrix` and use the original from `np.ndarray`.

```py
>>> import uncertainties as unc
>>> from iminuit.util import Matrix
>>> unc.correlated_values(m.values, super(Matrix, m.covariance))

(1.0072676945409316+/-0.058775382447305013,
 1.9660364327569773+/-0.09908674168467936)
```

**Comment by HDembinski** [comment] 2022-06-21 10:36
Thank you for this report, I will try to fix this, but I generally advice against using the `uncertainties` package. It is not a well-designed solution to the problem of error propagation. It introduces hidden dependencies between different variables in your program and it is very invasive since it replaces ordinary numbers and numpy arrays with its own implementations.

I recommend to use my library [jacobi](https://github.com/hDembinski/jacobi) for error propagation, which does not suffer from these issues and also works in complex cases where uncertainties fails.

**Comment by HDembinski** [comment] 2022-06-21 12:43
@APN-Pucky I cannot reproduce this error. My environment:
```
python==3.8.12
iminuit==2.11.2
uncertainties==3.1.7
```
Since you use an old Python version (3.6) which is no longer supported, you iminuit version is probably old. When you file a bug report, please check the latest version of iminuit. I am closing this, but feel free to reopen the issue if I am mistaken.

**Comment by APN-Pucky** [comment] 2022-06-21 12:55
Thanks for looking into it. I tested several python versions. 
Maybe you did something differently? I link a jupyter-notebook file what I ran exactly, but maybe it is still an issue in my environment (versions printed in it)?
https://gist.github.com/APN-Pucky/71029aadc19ba1f986f003d06d47bbf5

**Comment by HDembinski** [comment] 2022-06-21 15:35
Ok, I reopen to try your notebook.

**Comment by HDembinski** [comment] 2022-06-21 15:45
Ok, I can now reproduce the bug. It turns out that I fixed something in the develop branch of iminuit which fixes your issue. I did not actually test the bug on the latest release, because I do not remember making changes to this part of the library.

Anyway, I am about to release version 2.12.0 which fixes your issue, so I am closing this issue again. Please ping me again if the new release does not fix your problem.

**Closed by HDembinski** 2022-06-21 15:45 UTC
